//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDLocal_Conection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int IdProducto { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string NombreProducto { get; set; }
        public Nullable<int> CantidadExistente { get; set; }
        public Nullable<int> Precio { get; set; }
        public string estado { get; set; }
    }
}
